// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ntp.Persistance.Context;

#nullable disable

namespace Ntp.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("Ntp.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Elektronik",
                            Sort = 1,
                            SubCategoryId = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Moda",
                            Sort = 2,
                            SubCategoryId = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Oto, Bahçe, Yapı Merket",
                            Sort = 3,
                            SubCategoryId = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Bilgisayar ve Tablet",
                            Sort = 1,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Beyaz Eşye",
                            Sort = 2,
                            SubCategoryId = 1
                        });
                });

            modelBuilder.Entity("Ntp.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cat3DetailDescription1",
                            IsDeleted = false,
                            Title = "Cat3DetailTitle1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cat3DetailDescription2",
                            IsDeleted = false,
                            Title = "Cat3DetailTitle2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cat4DetailDescription1",
                            IsDeleted = false,
                            Title = "Cat4DetailTitle1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cat4DetailDescription2",
                            IsDeleted = true,
                            Title = "Cat4DetailTitle2"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cat4DetailDescription3",
                            IsDeleted = false,
                            Title = "Cat4DetailTitle3"
                        });
                });

            modelBuilder.Entity("Ntp.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Asus TUF Gaming FX607VU-RL017 Intel Core 5 210H 16GB 512GB SSD RTX4050 Freedos 16\" Taşınabilir Bilgisayar\r\nAsus TUF Gaming FX607VU-RL017 Intel Core 5 210H 16GB 512GB SSD RTX4050 Freedos 16\" Taşınabilir Bilgisayar\r\nAsus TUF Gaming FX607VU-RL017 Intel Core 5 210H 16GB 512GB SSD RTX4050 Freedos 16\" Taşınabilir Bilgisayar\r\nAsus TUF Gaming FX607VU-RL017 Intel Core 5 210H 16GB 512GB SSD RTX4050 Freedos 16\" Taşınabilir Bilgisayar\r\n",
                            IsDeleted = false,
                            Name = "Asus TUF Gaming FX607VU-RL017 Intel Core 5 210H 16GB 512GB SSD RTX4050 Freedos 16\" Taşınabilir Bilgisayar",
                            Price = 43899
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lenovo Thınkbook 16 21CY006FTR I5-1235U 8gb 512GB SSD 16\" Fdos\r\nLENOVO THINKBOOK 16 21CY006FTR i5-1235U 8GB 512GB SSD 16\" FDOSLenovo Thınkbook 16 21CY006FTR I5-1235U 8gb 512GB SSD 16\" Fdos\r\nLENOVO THINKBOOK 16 21CY006FTR i5-1235U 8GB 512GB SSD 16\" FDOSLenovo Thınkbook 16 21CY006FTR I5-1235U 8gb 512GB SSD 16\" Fdos\r\nLENOVO THINKBOOK 16 21CY006FTR i5-1235U 8GB 512GB SSD 16\" FDOSLenovo Thınkbook 16 21CY006FTR I5-1235U 8gb 512GB SSD 16\" Fdos\r\nLENOVO THINKBOOK 16 21CY006FTR i5-1235U 8GB 512GB SSD 16\" FDOS",
                            IsDeleted = false,
                            Name = "Lenovo Thınkbook 16 21CY006FTR I5-1235U 8gb 512GB SSD 16\" Fdos\r\n",
                            Price = 35000
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GENEL ÖZELLİKLER Boy: 70 cm Kol Boyu: 62 cm Desen: Düz Renk Kumaş.; Wellsoft Ek Özellik: Kapüşonlu “Ürünümüz wellsoft kumaştan üretilmiştir. Kumaşın doğası gereği ilk kullanımda hafif tüy bırakabilir, ancak bu durum ilk yıkamadan sonra tamamen ortadan kalkar. Bu, kumaşın özelliğinden kaynaklıdır ve ürünün kalitesine olumsuz bir etkisi yoktur.” YIKAMA ÖZELLİKLERİ - Maksimum 30 derecede yıkayınız.; - Yüksek ısıda ütü yapmayınız.; - Ağartıcı ve kimyasal madde kullanmayınız.; - Kurutma makinesine atmayınız.; KUMAŞ ÖZELLİKLERİ - Rahat ve yumuşak dokusu ile ön plana çıkan welsoft kumaşlar, tamamen polyesterden üretilmiş olan kumaş türleridir.; - Welsoft kumaş pek çok farklı özelliği ile günümüzde sağlık açısından büyük öneme sahip kumaş türlerinden biridir.; - özelliğe sahiptir.; - Alerji ve ile gibi durumlarda çocuklar ve yetişkinler için kullanılır.",
                            IsDeleted = false,
                            Name = "Kapüşonlu Polar Welsoft Peluş Hırka",
                            Price = 470
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yaman Market Kadın Uzun Kollu Önü Açık Desenli Şardonlu Dalgıç Ceket\r\nKadın Uzun Kollu önü Açık Desenli şardonlu Dalgıç CeketYaman Market Kadın Uzun Kollu Önü Açık Desenli Şardonlu Dalgıç Ceket\r\nKadın Uzun Kollu önü Açık Desenli şardonlu Dalgıç CeketYaman Market Kadın Uzun Kollu Önü Açık Desenli Şardonlu Dalgıç Ceket\r\nKadın Uzun Kollu önü Açık Desenli şardonlu Dalgıç Ceket",
                            IsDeleted = false,
                            Name = "Yaman Market Kadın Uzun Kollu Önü Açık Desenli Şardonlu Dalgıç Ceket",
                            Price = 1000
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Asus deletedAsus deletedAsus deletedAsus deletedAsus deletedAsus deletedAsus deletedAsus deletedAsus deletedAsus deleted",
                            IsDeleted = true,
                            Name = "Asus deleted",
                            Price = 10000
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Ntp.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ntp.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ntp.Domain.Entities.Detail", b =>
                {
                    b.HasOne("Ntp.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ntp.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
